name: 'AWS Run Pipeline Action for GitHub Actions'
description: 'Updates codepipeline release branch and runs'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  pipeline:
    description: 'The name of the AWS Codepipeline'
    required: true
outputs:
  started:
    description: 'Pipeline execution has begun'
runs:
  using: 'node12'
  main: 'dist/index.js'
